name: setup-action
description: setup action
inputs:
  build_type:
    description: CMake build type (Release, Debug, RelWithDebInfo, etc.)
    required: false
    default: Debug
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - name: Download embree
      shell: bash
      run: |
        curl -L -O https://github.com/embree/embree/releases/download/v3.13.0/embree-3.13.0.x86_64.linux.tar.gz \
        && tar -xf embree-3.13.0.x86_64.linux.tar.gz && mv embree-3.13.0.x86_64.linux embree \
        && rm embree-3.13.0.x86_64.linux.tar.gz

    - name: Configure CMake
      shell: bash
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{inputs.build_type}} \
          -Dembree_DIR=${{github.workspace}}/embree/lib/cmake/embree-3.13.0

    - name: Cache Workspace
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}
        key: ${{ runner.os }}-setup-cache
