name: Linux

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: .github/setup-action
      with:
        build_type: Debug

    - name: Enable Tests Target
      run: |
        cmake -B ${{github.workspace}}/build -DVIENNARAY_BUILD_TESTS=ON
   
    - name: Build tests
      # Build program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      run: ctest -C ${{env.BUILD_TYPE}}
      
